#!/usr/bin/env bash

# Copied and adjusted from https://github.com/NixOS/nix/issues/7165#issuecomment-2066723108.
get_build_targets() {
    local current_system=$(nix eval --impure --expr builtins.currentSystem --raw)
    nix flake show --json --no-eval-cache --system "$current_system" | jq --arg system "$current_system" '
        ["checks", "packages", "devShells"] as $tops |
        $tops[] as $top |
        .[$top][$system] |
        keys[] |
        "\($top).\($system).\(.)"
    ' | tr -d '"'
}

cashout() {
    local list_only=false
    local OPTIND
    while getopts "g" opt; do
        case ${opt} in
            g)
                list_only=true
                ;;
        esac
    done
    shift $((OPTIND - 1))

    if [ "$list_only" = true ]; then
        get_build_targets
        return
    fi

    local cache_name="$1"
    shift

    nix flake archive --json |
        jq -r '.path,(.inputs|to_entries[].value.path)' |
        cachix push "${cache_name}"

    for target in $(get_build_targets); do
        nix build --json ".#${target}" "$@" |
            jq -r '.[].outputs | to_entries[].value' |
            cachix push "${cache_name}"
    done
}

cashout "$@" frobware
